### PR TITLE
bug with strings with only leading ones

### PR DESCRIPTION
**Pull request by ralphtheninja**
I believe the string '1' should be decoded to '00' and not '0000'

### CODE REVIEW

**Comment by defunctzombie** [comment]
Have you confirmed the decode behavior with something else to ensure that decoding the address works as expected? The issue title has a question mark making it seem like this is unclear.

**Comment by ralphtheninja** [comment]
Yes it was unclear. I checked with this python code from wikipedia:

http://rosettacode.org/wiki/Bitcoin/address_validation#Python

Created a gist for it here

https://gist.github.com/ralphtheninja/8568026

**Comment by defunctzombie** [comment]
Does this need to be published or was it only internalized to base58 and doesn't affect validation or type inference?

**Comment by ralphtheninja** [comment]
Only internalized to base58. Doesn't break validation.

**Pull request merged**
